services:
  mass:
    build:
      context: . 
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/usr/src/server
    ports:
      - "3003:3003"
    command: ["cargo", "watch", "-x", "run"]
      
  database:
    image: redis/redis-stack
    volumes: 
      - ./data:/data
    ports:
      - "10001:10001"
      - "13333:8001"
       

